# Generated by Django 5.1.3 on 2025-03-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kinopoisk', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieshots',
            options={'verbose_name': 'Кадр из фильма', 'verbose_name_plural': 'Кадры из фильма'},
        ),
    ]
