# Generated by Django 5.1.3 on 2025-04-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_kinopoisk', '0003_alter_movieshots_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звёзды рейтинга', 'verbose_name_plural': 'Звёзды рейтинга'},
        ),
    ]
